// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/framewrk-hero-refined/HeroRefined.tsx": () => import("../components/mockups/framewrk-hero-refined/HeroRefined.tsx"),
  "./components/mockups/framewrk-home-brandrail-option1/OptionOne.tsx": () => import("../components/mockups/framewrk-home-brandrail-option1/OptionOne.tsx"),
  "./components/mockups/framewrk-who/Current.tsx": () => import("../components/mockups/framewrk-who/Current.tsx"),
  "./components/mockups/framewrk-who/LayoutStudy.tsx": () => import("../components/mockups/framewrk-who/LayoutStudy.tsx"),
  "./components/mockups/framewrk-who/StudioStory.tsx": () => import("../components/mockups/framewrk-who/StudioStory.tsx"),
  "./components/mockups/team-photo-study/ArchivalMatte.tsx": () => import("../components/mockups/team-photo-study/ArchivalMatte.tsx"),
  "./components/mockups/team-photo-study/Current.tsx": () => import("../components/mockups/team-photo-study/Current.tsx"),
  "./components/mockups/team-photo-study/EditorialFrame.tsx": () => import("../components/mockups/team-photo-study/EditorialFrame.tsx"),
  "./components/mockups/team-photo-study/FullWidthFeature.tsx": () => import("../components/mockups/team-photo-study/FullWidthFeature.tsx"),
  "./components/mockups/team-photo-study/LightCaptionBand.tsx": () => import("../components/mockups/team-photo-study/LightCaptionBand.tsx")
};
